#!/bin/bash

if [ ${1##*.} != "bin" ]; then
   echo Usage: ./program-backspin backspin-<version>.bin
   sleep 4
   exit
fi

sudo ./forth backspin-programmer.dic -s "open-one-backspin stm-run-from-flash"
