void w5500_hw_begin(uint8_t *mac_address);
int handlePackets ();
uint8_t read_byte(uint8_t block, uint16_t address);
uint16_t read_word(uint8_t block, uint16_t address);
void read_buf(uint8_t block, uint16_t address, uint8_t* pBuf, uint16_t len);
void write_byte(uint8_t block, uint16_t address, uint8_t wb);
void write_creg(uint16_t address, uint8_t wb);
void write_sreg(uint16_t address, uint8_t wb);
void write_word(uint8_t block, uint16_t address, uint16_t word);
void write_buf(uint8_t block, uint16_t address, uint8_t* pBuf, uint16_t len);
void setSn_CR(uint8_t cr);
uint16_t getSn_TX_FSR();
uint16_t getSn_RX_RSR();
void send_data(uint8_t *wizdata, uint16_t len);
void recv_data(uint8_t *wizdata, uint16_t len);
void recv_ignore(uint16_t len);
void sw_reset();
uint8_t getPHYCFGR();
void setPHYCFGR(uint8_t phycfgr);
void resetphy();
void discardFrame(uint16_t framesize);
uint16_t readFrameSize();
uint16_t readFrameData(uint8_t *buffer, uint16_t framesize);
uint16_t readFrame(uint8_t *buffer, uint16_t bufsize);
uint16_t sendFrame(uint8_t *buf, uint16_t len);
int linkoutput (void *netif, void *pbuf);
int w5500_netif_init ();
int start_with_dhclient ();
